/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CheckpointConceptIdRouteImport } from './routes/checkpoint.$conceptId'
import { Route as ClassroomConceptIdRouteImport } from './routes/classroom.$conceptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckpointConceptIdRoute = CheckpointConceptIdRouteImport.update({
  id: '/checkpoint/$conceptId',
  path: '/checkpoint/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomConceptIdRoute = ClassroomConceptIdRouteImport.update({
  id: '/classroom/$conceptId',
  path: '/classroom/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/progress': typeof ProgressRoute
  '/questions': typeof QuestionsRoute
  '/quizzes': typeof QuizzesRoute
  '/settings': typeof SettingsRoute
  '/checkpoint/$conceptId': typeof CheckpointConceptIdRoute
  '/classroom/$conceptId': typeof ClassroomConceptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/progress': typeof ProgressRoute
  '/questions': typeof QuestionsRoute
  '/quizzes': typeof QuizzesRoute
  '/settings': typeof SettingsRoute
  '/checkpoint/$conceptId': typeof CheckpointConceptIdRoute
  '/classroom/$conceptId': typeof ClassroomConceptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/library': typeof LibraryRoute
  '/progress': typeof ProgressRoute
  '/questions': typeof QuestionsRoute
  '/quizzes': typeof QuizzesRoute
  '/settings': typeof SettingsRoute
  '/checkpoint/$conceptId': typeof CheckpointConceptIdRoute
  '/classroom/$conceptId': typeof ClassroomConceptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/library'
    | '/progress'
    | '/questions'
    | '/quizzes'
    | '/settings'
    | '/checkpoint/$conceptId'
    | '/classroom/$conceptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/library'
    | '/progress'
    | '/questions'
    | '/quizzes'
    | '/settings'
    | '/checkpoint/$conceptId'
    | '/classroom/$conceptId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/library'
    | '/progress'
    | '/questions'
    | '/quizzes'
    | '/settings'
    | '/checkpoint/$conceptId'
    | '/classroom/$conceptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LibraryRoute: typeof LibraryRoute
  ProgressRoute: typeof ProgressRoute
  QuestionsRoute: typeof QuestionsRoute
  QuizzesRoute: typeof QuizzesRoute
  SettingsRoute: typeof SettingsRoute
  CheckpointConceptIdRoute: typeof CheckpointConceptIdRoute
  ClassroomConceptIdRoute: typeof ClassroomConceptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkpoint/$conceptId': {
      id: '/checkpoint/$conceptId'
      path: '/checkpoint/$conceptId'
      fullPath: '/checkpoint/$conceptId'
      preLoaderRoute: typeof CheckpointConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom/$conceptId': {
      id: '/classroom/$conceptId'
      path: '/classroom/$conceptId'
      fullPath: '/classroom/$conceptId'
      preLoaderRoute: typeof ClassroomConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LibraryRoute: LibraryRoute,
  ProgressRoute: ProgressRoute,
  QuestionsRoute: QuestionsRoute,
  QuizzesRoute: QuizzesRoute,
  SettingsRoute: SettingsRoute,
  CheckpointConceptIdRoute: CheckpointConceptIdRoute,
  ClassroomConceptIdRoute: ClassroomConceptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
